# Generated by Django 2.1.5 on 2022-07-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diss', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Location',
        ),
    ]
