# Generated by Django 2.1.5 on 2022-08-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diss', '0005_auto_20220805_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
